
pipelines:
  default:
    - step:
        name: deploy test
        deployment: test
        image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
        script:
          - pip install awscli
          - pip install aws-sam-cli
          - bash deploy.sh
#        services:
#          - database

  branches:
    master:
      - step:
          name: deploy production
          deployment: production
          image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
          script:
            - pip install awscli
            - pip install aws-sam-cli
            # - bash deploy.sh
            - sam build && sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-product
            - sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-product

    develop:
      - step:
          name: deploy staging
          deployment: staging
          image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
          script:
            - pip install awscli
            - pip install aws-sam-cli
            # - bash deploy.sh
            - sam build && sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-staging
            - sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-staging

#definitions:
#  services:
#    database:
#      image: mysql:5.7
#      environment:
#        MYSQL_ROOT_PASSWORD: hogehoge
#        MYSQL_DATABASE:hoge_db
#        MYSQL_USER: 'root'
