
pipelines:
  default:
    - step:
      name: Deploy to test
      image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
        aws:
          access-key: $AWS_ACCESS_KEY_ID
          secret-key: $AWS_SECRET_ACCESS_KEY
      deployment: test
      script:
        # - pip install --user aws-sam-cli
        - pip install awscli
        - pip install aws-sam-cli
        - bash deploy.sh
#        services:
#          - database

#definitions:
#  services:
#    database:
#      image: mysql:5.7
#      environment:
#        MYSQL_ROOT_PASSWORD: hogehoge
#        MYSQL_DATABASE:hoge_db
#        MYSQL_USER: 'root'
