image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。

pipelines:
  default:
    - step:
        script:
          # - pip install --user aws-sam-cli
          - pip install awscli
          - pip install aws-sam-cli
          - bash deploy.sh
#        services:
#          - database

#definitions:
#  services:
#    database:
#      image: mysql:5.7
#      environment:
#        MYSQL_ROOT_PASSWORD: hogehoge
#        MYSQL_DATABASE:hoge_db
#        MYSQL_USER: 'root'
