# version 1
# TODO TEST
# TODO S3へアップロードしたパッケージを削除する処理

pipelines:
  default:
    - step:
        name: deploy test
        deployment: test
        image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
        script:
          - pip install awscli
          - pip install aws-sam-cli
          - bash deploy.sh
#        services:
#          - database

  branches:
    master:
      - step:
          name: deploy production
          deployment: production
          image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
          script:
            - pip install awscli
            - pip install aws-sam-cli
            # - bash deploy.sh
            - sam build && sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-product
            - sam deploy --template-file packaged.yaml --stack-name sam-app-prod --capabilities CAPABILITY_IAM --region ap-northeast-1 --parameter-overrides Env=prod

    develop:
      - step:
          name: deploy staging
          deployment: staging
          image: python:3.6.8 # CIをまわすDocker image。Docker Hubにあるやつはなんでも使える。
          script:
            - pip install awscli
            - pip install aws-sam-cli
            - bash deploy_develop.sh
            # - sam build && sam package --output-template-file packaged.yaml --s3-bucket jsl-aws-sam-staging
            # - sam deploy --template-file packaged.yaml --stack-name sam-app-stg --capabilities CAPABILITY_IAM --region ap-northeast-1 --parameter-overrides Env=stg

#definitions:
#  services:
#    database:
#      image: mysql:5.7
#      environment:
#        MYSQL_ROOT_PASSWORD: hogehoge
#        MYSQL_DATABASE:hoge_db
#        MYSQL_USER: 'root'
